[package]
name = "esp32-bus-pirate-bus-modes"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
embedded-hal.workspace = true
heapless.workspace = true
log.workspace = true

[features]
default = []
